name: Generate GraphQL Schema

on:
  push:
    branches:
      - main  # Trigger on push to main or change as needed

jobs:
  generate-schema:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Start Test Server in Background
      - name: Start Test Server
        run: |
          tsx ./src/index.ts &  # Start the server
          sleep 5  # Wait for the server to be up

      # Step 5: Generate Schema Files (using npm script)
      - name: Run GraphQL Codegen
        run: npm run generate:schema

      # Step 6: Check for Schema Changes
      - name: Verify Schema Sync
        run: |
          git diff --exit-code || (echo "Schema is out of sync. Please commit changes." && exit 1)

      # Optional: Save generated schema artifacts for later inspection
      - name: Upload Generated Schema
        uses: actions/upload-artifact@v3
        with:
          name: schema-artifacts
          path: |
            schema.json
            schema.md
