name: Generate Schema in CI

on:
  push:
    branches:
      - main

jobs:
  generate-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Generate Schema
        run: npm run generate:schema

      - name: Check for Schema Changes
        run: |
          git diff --quiet schema.json schema.md || (
            echo "Schema files are out-of-date. Please regenerate them locally." && exit 1
          )
